version: "3.3"

services:
  dashboard:
    image: nz_image_url
    restart: always
    volumes:
      - ./data:/dashboard/data
      - ./theme-custom/template:/dashboard/resuorce/template/theme-default:ro
      - ./theme-custom/static:/dashboard/resuorce/static/theme-default:ro
    ports:
      - nz_site_port:80
      - nz_grpc_port:nz_grpc_port
