name: Sync Fork

on:
  schedule:
    - cron: '0 18 */3 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2
        with:
          owner: naiba
          base: master
          head: master
          auto_approve: true
          retries: 2
          retry_after: 30
          pr_title: 同步上游
